# Generated by Django 6.0.5 on 2026-06-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name=20)),
                ('price', models.IntegerField()),
                ('quabtity', models.IntegerField()),
                ('description', models.TextField()),
                ('brand', models.CharField(verbose_name=20)),
            ],
        ),
    ]
