# Generated by Django 6.0.5 on 2026-06-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quabtity',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
