# Generated by Django 6.0.5 on 2026-05-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('place', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
